# Generated by Django 3.2 on 2021-04-21 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_modelling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='System_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_type', to='system_modelling.model_type')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='ebook',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_author',
        ),
        migrations.DeleteModel(
            name='Ebook',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
